/** Use this file to specify the messaging used by your brand */

export const messages = {
  en: {
    portalName: `Data Submission Portal`,
    logo: `CZN_Logo.png`, // Must be placed inside `/src/assets/img/` directory
    portalNameShort: `DSP`,
    hubName: `CZ Hub`,
    home: {
      banner: {
        title: `Critical Zone Collaborative Network`,
        subtitle: `Data Submission Portal`,
        portalLinkHint: `Looking for CZNet data?`,
        portalLinkText: `Visit our data discovery portal`,
      },
      submitData: {
        title: `Submit Your Data and Research Products`,
        description: `Created for the Critical Zone Collaborative Network (CZCN), this
        Data Submission Portal provides tools for determining which
        repository to use for data submission along with enhanced submission
        tools to encourage data standards, complete metadata, and
        high-quality submissions.`,
        points: [
          {
            title: `Which repository?`,
            description: `Use the Portal's repository recommendation system to determine which repository is right for submitting your research products.

          `,
          },
          {
            title: `Which format?`,
            description: `Use CZ community recommendations to decide on formats and conventions for your data files.`,
          },
          {
            title: `Which metadata?`,
            description: `Use the Portal's submission tools to ensure your metadata are complete and that your data are well described.`,
          },
        ],
      },
    },
    footer: {
      hubLink: `https://criticalzone.org/hub`,
      orgName: `CZNet`,
      orgLink: `https://www.criticalzone.org/`,
      repoUrl: `https://github.com/cznethub/dsp`,
      reportIssuesUrl: `https://github.com/cznethub/dsp/issues`,
    },
    about: {
      body: [
        `The Critical Zone Collaborative Network (CZNet) is the next phase of
        NSF’s Critical Zone research program, comprised of nine Thematic Cluster
        study areas with a wide range of geological, climatic, and land use
        settings that provide an opportunity to better understand the evolution
        and function of the critical zone.`,
        `The CZNet builds upon the outcomes of the Critical Zone Observatories
        (CZO) to address significant interdisciplinary scientific questions at
        the regional and national scale, and develop predictive models of
        complex CZ phenomena. The nine Thematic Clusters represent an array of
        CZ locations selected on the basis of a unifying scientific theme. Each
        Cluster has several geographic locations encompassing multiple of
        watersheds that facilitate investigations of environmental gradients
        relevant to the Cluster research theme. CZNet showcases convergent
        science and multidisciplinary teams. The CZ Coordinating Hub manages the
        standardization, archival, and access of the data generated by the
        Clusters, convenes regular meetings of the Thematic Clusters, and plans
        for future research infrastructure needs of the network. The Hub
        supports national outreach activities and organizes workshops that
        engage the larger CZ community. These activities enhance scientific
        progress within the domains of CZ research and encourage the
        participation of a broad range of scientists from various disciplines,
        at different career stages, and from groups that are traditionally
        underrepresented in the sciences.`,
      ],
    },
  },
};
