import { CzISubmission, CzEnumSubmissionStatus, CzEnumRepositories } from "./types";

export const SUBMISSIONS: CzISubmission[] = [
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  },
  {
    title: 'A really awesome dataset',
    authors: ['Jeffery S. Horsburgh', 'Scott Black', 'Kerstin Lehnert'],
    repository: CzEnumRepositories.hydroShare,
    date: new Date(),
    status: CzEnumSubmissionStatus.draft,
    identifier: 'http://doi.org/hs.xxxxxxx.123456789',
  }
]