<template>
  <div class="cz-about">
    <div id="panel-left" class="has-text-centered has-text-shadow"
      :style="{ 'background-image': 'linear-gradient(rgb(0 52 82 / 31%), rgba(0, 0, 0, 0)), url(' + require('@/assets/img/bg-4.png') + ')' }">
    </div>
    <div id="panel-right" class="">
      <h1 class="">About the Critical Zone Collaborative Network</h1>
    <hr>
    <div class="">
      The Critical Zone Collaborative Network (CZNet) is the next phase of NSF’s Critical Zone research program, comprised of nine Thematic Cluster study areas with a wide range of geological, climatic, and land use settings that provide an opportunity to better understand the evolution and function of the critical zone.
    </div>
    <p>
      The CZNet builds upon the outcomes of the Critical Zone Observatories (CZO) to address significant interdisciplinary scientific questions at the regional and national scale, and develop predictive models of complex CZ phenomena.

The nine Thematic Clusters represent an array of CZ locations selected on the basis of a unifying scientific theme. Each Cluster has several geographic locations encompassing multiple of watersheds that facilitate investigations of environmental gradients relevant to the Cluster research theme. CZNet showcases convergent science and multidisciplinary teams.

The CZ Coordinating Hub manages the standardization, archival, and access of the data generated by the Clusters, convenes regular meetings of the Thematic Clusters, and plans for future research infrastructure needs of the network. The Hub supports national outreach activities and organizes workshops that engage the larger CZ community. These activities enhance scientific progress within the domains of CZ research and encourage the participation of a broad range of scientists from various disciplines, at different career stages, and from groups that are traditionally underrepresented in the sciences.
    </p>
    </div>
    
  </div>
</template>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator'

  @Component({
    name: 'cz-about',
    components: { },
  })
  export default class CzAbout extends Vue {

  }
</script>

<style lang="scss" scoped>
    .cz-about {
    margin: -17px;
    height: calc(100% + 34px);
    // background-color: #edf0f1;
  }

  #panel-left {
    height: 100%;
  }

  #panel-left {
    padding-top: 8rem;
    background-size: cover;
  }

  #panel-right {
    max-width: 60rem;
    padding: 4rem;
    flex-direction: column;
  }
</style>
