/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'Cz.about': typeof import('./components/about/cz.about.vue')['default']
    'Cz.account': typeof import('./components/profile/cz.account.vue')['default']
    'Cz.authorize': typeof import('./components/authorize/cz.authorize.vue')['default']
    'Cz.authorizedRepositories': typeof import('./components/profile/cz.authorized-repositories.vue')['default']
    'Cz.contact': typeof import('./components/contact/cz.contact.vue')['default']
    'Cz.folderStructure': typeof import('./components/new-submission/cz.folder-structure.vue')['default']
    'Cz.footer': typeof import('./components/base/cz.footer.vue')['default']
    'Cz.home': typeof import('./components/home/cz.home.vue')['default']
    'Cz.login': typeof import('./components/account/cz.login.vue')['default']
    'Cz.newSubmission': typeof import('./components/new-submission/cz.new-submission.vue')['default']
    'Cz.newSubmissionActions': typeof import('./components/new-submission/cz.new-submission-actions.vue')['default']
    'Cz.profile': typeof import('./components/profile/cz.profile.vue')['default']
    'Cz.quickStartGuide': typeof import('./components/quick-start-guide/cz.quick-start-guide.vue')['default']
    'Cz.recommendationCard': typeof import('./components/recommendations/cz.recommendation-card.vue')['default']
    'Cz.recommendations': typeof import('./components/recommendations/cz.recommendations.vue')['default']
    'Cz.recommendationsQuestionnaire': typeof import('./components/recommendations/cz.recommendations-questionnaire.vue')['default']
    'Cz.registerDataset': typeof import('./components/register-dataset/cz.register-dataset.vue')['default']
    'Cz.registerDatasetDialog': typeof import('./components/register-dataset/cz.register-dataset-dialog.vue')['default']
    'Cz.repositorySubmitCard': typeof import('./components/submit/cz.repository-submit-card.vue')['default']
    'Cz.resources': typeof import('./components/resources/cz.resources.vue')['default']
    'Cz.submissions': typeof import('./components/submissions/cz.submissions.vue')['default']
    'Cz.submit': typeof import('./components/submit/cz.submit.vue')['default']
    'Cz.viewSubmission': typeof import('./components/view-submission/cz.view-submission.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
