name: Cypress Tests with Dependency and Artifact Caching
# https://docs.cypress.io/guides/continuous-integration/github-actions

on: push

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: dist

  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Cypress run component tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run cypress:run-component

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v5
        with:
          start: npx serve -s dist -p 8080
          wait-on: 'http://localhost:8080'
          browser: chrome
          command: npm run cypress:run-e2e
        # or install start-server-and-test and do:
        # run: npm run test-e2e
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos